name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache Python dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/uv
          .venv
        key: ${{ runner.os }}-python-${{ hashFiles('requirements-test.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Install just
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin

    - name: Install dependencies
      run: |
        just install-deps

    - name: Cache Playwright browsers
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('requirements-test.txt') }}
        restore-keys: |
          ${{ runner.os }}-playwright-

    - name: Install Playwright browsers
      run: |
        . .venv/bin/activate && playwright install --with-deps chromium

    - name: Start services
      run: |
        just start-all
        # Give services extra time to stabilize
        sleep 15
      env:
        DOCKER_BUILDX: "1"

    - name: Check service status
      run: |
        just status
        docker logs syftbox-server --tail 50
        docker logs syftbox-client-client1-syftbox-net --tail 50
        docker logs syftbox-client-client2-syftbox-net --tail 50

    - name: Fix permissions
      run: |
        just fix-permissions

    - name: Run integration tests
      run: |
        just test
      env:
        PYTEST_TIMEOUT: 300

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          pytest-report.html
          .pytest_cache/

    - name: Collect logs on failure
      if: failure()
      run: |
        echo "=== Server Logs ==="
        docker logs syftbox-server || true
        echo "=== Client1 Logs ==="
        docker logs syftbox-client-client1-syftbox-net || true
        echo "=== Client2 Logs ==="
        docker logs syftbox-client-client2-syftbox-net || true
        echo "=== Docker PS ==="
        docker ps -a
        echo "=== Test Client Directories ==="
        ls -la clients/ || true

    - name: Cleanup
      if: always()
      run: |
        just clean || true